name: Bitbone
favicon: null
layout_spectrum: 0.22724
typography_spectrum: 0.19786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#363c42'
    - '#a98c19'
    - '#f3f3f3'
    - '#2788ae'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
